### ISSUE TITLE
escodegenOptions why not set sourceMapRoot ?

### ISSUE THREAD

**Issue by okoala** [power-assert-js/espower-source#16]
https://github.com/power-assert-js/espower-source/blob/master/index.js#L193

My question is when i debug test file, vscode cannot find the correct file path.

![image](https://cloud.githubusercontent.com/assets/2127199/25690090/7c4a217a-30c0-11e7-837d-46f67391bf5d.png)

vscode log:

```bash
SourceMaps.getMapForGeneratedPath: Using inlined sourcemap in d:\Code\github\egg-example\test\app\controller\home.test.js
SourceMap: creating for d:\Code\github\egg-example\test\app\controller\home.test.js
SourceMap: sourceRoot: undefined
SourceMap: sources: ["test\\app\\controller\\home.test.js"]
SourceMap: no sourceRoot specified, using script dirname: d:\Code\github\egg-example\test\app\controller
Warning: sourceMapPathOverrides entry does not map to an absolute path - "webpack:///./*": "${cwd}/*"
Warning: sourceMapPathOverrides entry does not map to an absolute path - "webpack:///*": "*"
Warning: sourceMapPathOverrides entry does not map to an absolute path - "meteor://💻app/*": "${cwd}/*"
SourceMaps.scriptParsed: d:\Code\github\egg-example\test\app\controller\home.test.js was just loaded and has mapped sources: ["d:\\Code\\github\\egg-example\\test\\app\\controller\\test\\app\\controller\\home.test.js"]
SourceMaps.setBP: Mapped d:\Code\github\egg-example\test\app\controller\test\app\controller\home.test.js to d:\Code\github\egg-example\test\app\controller\home.test.js
SourceMaps.setBP: Mapped d:\Code\github\egg-example\test\app\controller\test\app\controller\home.test.js:7:1 to d:\Code\github\egg-example\test\app\controller\home.test.js:37:9
SourceMaps.setBP: Mapped d:\Code\github\egg-example\test\app\controller\test\app\controller\home.test.js:14:1 to d:\Code\github\egg-example\test\app\controller\home.test.js:54:9
SourceMaps.setBP: SourceMaps are enabled but d:\Code\github\egg-example\test\app\controller\home.test.js is a runtime script
SourceMaps.setBP: Mapped d:\Code\github\egg-example\test\app\controller\home.test.js:37:9 to d:\Code\github\egg-example\test\app\controller\test\app\controller\home.test.js:7
SourceMaps.setBP: Mapped d:\Code\github\egg-example\test\app\controller\home.test.js:54:9 to d:\Code\github\egg-example\test\app\controller\test\app\controller\home.test.js:14
```

but i when i set `escodegenOptions.sourceMapRoot` and it works.

```js
if (options.sourceRoot) {
    escodegenOptions.sourceMapRoot = options.sourceRoot;
}
```

**Comment by okoala** [comment]
eggjs/egg#839

**Comment by twada** [comment]
@okoala Thank you for reporting. I'll working on this.

**Comment by twada** [comment]
Let me explain the background of this issue.

I have been tackling with sourcemap issues for a couple of years, and for filepaths, had faced 2 problems. 

- Pointing correct path from sourcemap is very difficult problem since there are many file manipulations while building js files.
- `sourceRoot` option is originally intended to used by browsers, pointing paths from content root.

These are why I don't use `sourceRoot`.

Then I've found that `sourcesContent` property for the rescue. If original code is embedded in `sourcesContent` property, debuggers use content of `sourcesContent` instead of reading original files from URL/filesystem. It'd solved annoying path problems and security issues.

Chrome, Firefox, Safari and WebStorm/IntelliJ uses `sourcesContent` for debugging.

How about VSCode?  Unfortunately, VSCode ignores the sourcesContent "by design" (OMG).
- [Source maps containing sources are not supported (sourcesContent)](https://github.com/Microsoft/vscode-chrome-debug/issues/60#issuecomment-163514786)
- [Source maps don't work when attaching to running code](https://github.com/Microsoft/vscode/issues/936#issuecomment-161690001)

I'm going to accept and fix this issue for now since Chrome/Firefox/Safari and WebStorm will continue to use `sourcesContent` for debugging. However, if there are some issues caused by `sourceRoot`, I'll revert the fix here and try to fix this again at `espower-loader` level.

**Comment by twada** [comment]
@okoala [espower-source 2.2.0](https://github.com/power-assert-js/espower-source/blob/master/CHANGELOG.md#220-2017-05-05) is out. Would you give it a try?

**Comment by okoala** [comment]
@twada  thinks a lot， i try it now.

**Comment by twada** [comment]
Closing for now. Please feel free to reopen this issue when reproduced.
